all:
  children:
    web:
      hosts:
        127.0.0.1:
      vars:
        ansible_port: 2222
        ansible_user: vagrant
        ansible_connection: ssh
        ansible_ssh_private_key_file: .vagrant/machines/web/virtualbox/private_key
    db:
      hosts:
        127.0.0.1:
      vars:
        ansible_port: 2222
        ansible_user: vagrant
        ansible_connection: ssh
        ansible_ssh_private_key_file: .vagrant/machines/db/virtualbox/private_key
    redis:
      hosts:
        127.0.0.1:
      vars:
        ansible_port: 2222
        ansible_user: vagrant
        ansible_connection: ssh
        ansible_ssh_private_key_file: .vagrant/machines/redis/virtualbox/private_key

