---
- name: Add web and batch sudo alias
  include: both_role.yml
  tags:
    - both_role

- name: Add batch sudo alias
  include: sidekiq.yml
  tags:
    - batch

- name: Add web sudo alias
  include: unicorn.yml
  tags:
    - web

