---
- name: Add web and batch sudo alias
  import_tasks: both_role.yml
  when: type == 'both_role'

- name: Add batch sudo alias
  import_tasks: sidekiq.yml
  when: type == 'batch'

- name: Add web sudo alias
  import_tasks: unicorn.yml
  when: type == 'web'

