- src: zzet.rbenv
- src: geerlingguy.mysql
- src: DavidWittman.redis
- src: geerlingguy.git
- src: nickjj.user
- src: ocha.yarn
- src: https://github.com/DrTom/ansible-role-chromedriver
  name: DrTom.chrome-driver
- src: cmprescott.chrome

