---
- hosts: web
  become: yes
  become_method: sudo
  vars_files:
    - ".secrets/{{ secret_env }}.yml"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    rbenv:
      env: system
      version: v1.1.1
      default_ruby: 2.4.2
      rubies:
        - version: 2.4.2
    nodejs:
      version: 9
    mysql_root_password: "{{ mysql.root_password }}"
    mysql_databases:
      - name: "{{ mysql.application_database }}"
        encoding: utf8mb4
        collation: utf8mb4_bin
    mysql_users:
      - name: "{{ mysql.application_username }}"
        host: "%"
        password: "{{ mysql.application_user_password }}"
        priv: "{{ mysql.application_database }}.*:ALL"
    redis_bind: 127.0.0.1
    redis_version: 4.0.7
    redis_verify_checksum: true
    redis_checksum: "sha256:1bba546d44fb40e1fd8be1a15e1a9cc6484bceeea0bbd52919eebc656661ecd1"
    git_install_from_source: true
    git_install_from_source_force_update: true
    git_version: 2.16.1
    user_local_ssh_key_path: "{{ deploy.ssh_pubkey_path }}"
  roles:
    - galaxy/geerlingguy.git
    - galaxy/zzet.rbenv
    - roles/nodejs
    - { role: roles/mysql-dependencies, become: yes }
    - { role: galaxy/geerlingguy.mysql, become: yes }
    - galaxy/DavidWittman.redis
    - galaxy/cmprescott.chrome
    - galaxy/nickjj.user
    - roles/application-deploy-path
    - roles/bundler
    - galaxy/ocha.yarn

