---
- hosts: web
  become: yes
  become_method: sudo
  vars_files:
    - ".secrets/{{ secret_env }}.yml"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    rbenv:
      env: system
      version: v1.1.1
      default_ruby: 2.4.2
      rubies:
        - version: 2.4.2
    nodejs:
      version: 9
    mysql_root_password: "{{ mysql.root_password }}"
    mysql_databases:
      - name: "{{ mysql.application_database }}"
        encoding: utf8mb4
        collation: utf8mb4_bin
    mysql_users:
      - name: "{{ mysql.application_username }}"
        host: "%"
        password: "{{ mysql.application_user_password }}"
        priv: "{{ mysql.application_database }}.*:ALL"
  roles:
    - galaxy/zzet.rbenv
    - roles/nodejs
    - { role: roles/mysql-dependencies, become: yes }
    - { role: galaxy/geerlingguy.mysql, become: yes }

