---
- name: Create deploy user environment-variables directory
  file:
    path: "/etc/systemd/user/{{ application.deploy_user }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Upload environment variables file
  template:
    src: env
    dest: /etc/systemd/user/{{ application.deploy_user }}/env
    owner: root
    group: root
    mode: 0644

