---
- hosts: db
  become: yes
  become_method: sudo
  vars_files:
    - ".secrets/{{ secret_env }}.yml"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_password: "{{ mysql.root_password }}"
    mysql_databases:
      - name: "{{ mysql.application_database }}"
        encoding: utf8mb4
        collation: utf8mb4_bin
    mysql_users:
      - name: "{{ mysql.application_username }}"
        host: "%"
        password: "{{ mysql.application_user_password }}"
        priv: "{{ mysql.application_database }}.*:ALL"
  roles:
    - roles/apt
    - roles/mysql-dependencies
    - galaxy/geerlingguy.mysql
